### ISSUE TITLE
Reply-To parameter missing

### ISSUE THREAD

**Issue by edgarwideman** [resendlabs/resend-php-example#6]
Hi there, love this API, but seems to be extremely limited as to what you can do with it. The example only shows basic to, from, subject, and body parameters. I need to set a Reply-To value in the header, and there seems to not be a way to do this. Could someone confirm if this is missing or if I am just dumb and can't find it? If it is not an option, consider this a feature request. Thanks!

**Comment by jayanratna** [comment]
Hey @edgarwideman, I will get the example updated.

You can set the reply to by passing a `reply_to` body parameter. Like so:

```php
    $resend->emails->send([
        'from' => 'Acme <onboarding@resend.dev>',
        'to' => ['delivered@resend.dev'],
        'reply_to' => 'replyto@resend.dev',
        'subject' => 'Hello world',
        'html' => '<strong>It works!</strong>',
    ]);
```

**Comment by edgarwideman** [comment]
Awesome! You're the best! Thanks a ton. 🎉
